apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: app
  namespace: default
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
        hasuraService: custom
    spec:
      containers:
      - image: hasura/hello-world:latest
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
status: {}
