apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: ClusterIP
status:
  loadBalancer: {}
